// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BlogFooter: typeof import('./BlogFooter.vue')['default']
    BlogHeader: typeof import('./BlogHeader.vue')['default']
    HelloWorld: typeof import('./HelloWorld.vue')['default']
  }
}

export { }
