// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleTextarea: typeof import('./components/article/ArticleTextarea.vue')['default']
    BlogFooter: typeof import('./components/BlogFooter.vue')['default']
    BlogHeader: typeof import('./components/BlogHeader.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    UserInput: typeof import('./components/user-authentication/UserInput.vue')['default']
    UserSubmitBtnTip: typeof import('./components/user-authentication/UserSubmitBtnTip.vue')['default']
  }
}

export { }
